### ISSUE TITLE
Remove unit test template

### ISSUE THREAD

**Issue by wk-j** [mahasak/ETDA.Invoice.Api#14]
This file is unused 

https://github.com/mahasak/ETDA.Invoice.Api/blob/3e57113106d14af2c2c7150327164b6e74132fc2/ETDA.Invoice.Api.UnitTests/UnitTest1.cs#L1-L13

**Comment by varokas** [comment]
We need at least one test for `dotnet test` not to fail. I'll keep this to remind us to do it once #8 is merged.

**Comment by aixasz** [comment]
@varokas We have some tests on https://github.com/mahasak/ETDA.Invoice.Api/pull/10, and it's already merged.
