### ISSUE TITLE
Code smell in DateHelpers.cs

### ISSUE THREAD

**Issue by aixasz** [mahasak/ETDA.Invoice.Api#7]
https://github.com/mahasak/ETDA.Invoice.Api/blob/master/ETDA.Invoice.Api/Helpers/DateHelper.cs#L22 

This does seem like hack. We can get rid and use `DateTime.Parse` or `Convert.ToDateTime` instead of this.

**Comment by mahasak** [comment]
@aixasz yes i think we need to review the API structure
